hushbot:
  general:
    prefix: 'hush!'
  channels:
    log_channel: 000000000000000000
    alert_channel: 000000000000000000
  permissions:
    staff_role: 000000000000000000
  filters:
    profanity:
      enable: true
      action: "alert"