version: '3.2'

networks:
  hushbot:

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS:-password123}
    ports:
     - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      hushbot:

  bot:
    build:
      context: ./
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USER=${REDIS_USER:-default}
      - REDIS_PASS=${REDIS_PASS:-password123}
    depends_on:
      - redis
    networks:
      hushbot:

volumes:
  redis-data:
  redis-conf: